sudo: required
services:
  - docker

before_install:
  - docker build -t mustafat/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mustafat/react-test npm test

after_success:
  - docker build -t mustafat/multi-client ./client
  - docker build -t mustafat/multi-nginx ./nginx
  - docker build -t mustafat/multi-server ./server
  - docker build -t mustafat/multi-worker ./worker
#Log in to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mustafat/multi-client
  - docker push mustafat/multi-nginx
  - docker push mustafat/multi-server
  - docker push mustafat/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-413756166421"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY